# Generated by Django 2.2.13 on 2023-02-24 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0003_remitosdet_remitosenc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remitosenc',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='remitosenc',
            name='uc',
        ),
        migrations.DeleteModel(
            name='RemitosDet',
        ),
        migrations.DeleteModel(
            name='RemitosEnc',
        ),
    ]
